application: boot-cssi-2017
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: boot1.ico
  upload: boot1\.ico

- url: /javascript
  static_dir: javascript

- url: /img
  static_dir: img

- url: /scss
  static_dir: scss


- url: /stylesheet
  static_dir: stylesheet

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
